
// about page
export default function RegisterCompney() {
    const a = 0
    return (<div className="float-end " style={{ width: "85%" }}>
        <h1>Register Compney</h1>
        <p>Product depth refers to the variation in products that a company offers within one product line. Knowing about a line's product depth can help companies understand the degree of differentiation between their products, which can inform which products they continue to sell and where there might be a need to create a new product. Product depth can include details like a product's size, flavor, useful life and more. For example, if a company has a product line of potato chips that includes five flavors and three bag sizes, the product depth for the line is 15.Product depth refers to the variation in products that a company offers within one product line. Knowing about a line's product depth can help companies understand the degree of differentiation between their products, which can inform which products they continue to sell and where there might be a need to create a new product. Product depth can include details like a product's size, flavor, useful life and more. For example, if a company has a product line of potato chips that includes five flavors and three bag sizes, the product depth for the line is 15.Paragraphs are used in writing to introduce new sections of a story, characters or pieces of information. Paragraphs help readers to enjoy what has been written because they break text up into easy-to-read sections.Paragraphs are used in writing to introduce new sections of a story, characters or pieces of information. Paragraphs help readers to enjoy what has been written because they break text up into easy-to-read sections.Paragraphs are used in writing to introduce new sections of a story, characters or pieces of information. Paragraphs help readers to enjoy what has been written because they break text up into easy-to-read sections.Paragraphs are used in writing to introduce new sections of a story, characters or pieces of information. Paragraphs help readers to enjoy what has been written because they break text up into easy-to-read sections.</p>
    </div>
    )
}
